services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: bobapp-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/joke"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: bobapp-frontend
    ports:
      - "8082:80"
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    name: bobapp-network
